Skip to content
Search or jump to…
Pull requests
Issues
Marketplace
Explore
 
@aryavorskiy 
aryavorskiy
/
TopologicalMarkers
Public
Code
Issues
Pull requests
Actions
Projects
Wiki
Security
Insights
Settings
TopologicalMarkers/.github/workflows/codecov.yml
@aryavorskiy
aryavorskiy Update codecov.yml
Latest commit d7c9f01 on 21 Nov 2021
 History
 1 contributor
43 lines (37 sloc)  1.29 KB

# This is a basic workflow to help you get started with Actions

name: Codecov

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1.6'
      - uses: julia-actions/julia-runtest@latest
        env:
          GKSwstype: "100"
      - uses: julia-actions/julia-processcoverage@v1
        env:
          GKSwstype: "100"
      - uses: codecov/codecov-action@v1
        with:
          file: ./lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}
TopologicalMarkers/codecov.yml at master · aryavorskiy/TopologicalMarkers
